### ISSUE TITLE
SVG element not shown in Chrome

### ISSUE THREAD

**Issue by jkvatne** [LukeWoodward/SplitsBrowser#86] opened 2023-06-21 11:14 UTC
I have a demo at https://www.nook.no/split.php?file=./resultater2023/Trening_20.06.23.csv
It will display the graphs ok in edge and firefox, but not on chrome. Can this be fixed? 

It uses the following libraries:  "https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js" and "https://ajax.googleapis.com/ajax/libs/d3js/5.16.0/d3.min.js". I have tried many other versions but with no luck.

**Comment by jkvatne** [comment] 2023-06-22 06:37
Here is a screenshot.
![image](https://github.com/LukeWoodward/SplitsBrowser/assets/11456832/4f659a36-0ca3-4e26-892e-02e50691a1d1)

**Comment by jkvatne** [comment] 2023-06-22 06:39
Then I went to Chrome Settings, and did a "Reset Settings", and now miraculously it works perfectly!  There must have been a setting that affected the display, but I do not know which.

**Comment by LukeWoodward** [comment] 2023-06-23 18:53
Hi Jan,

Thanks for getting back to me and letting me know the issue has been sorted out for you. I suspected it might have been a problem at your end, because I couldn't reproduce the problem myself. You also mentioned that the graphs display okay in Edge. Edge now uses the same rendering engine as Chrome, so if there was an issue displaying the graphs in one of them then I would expect the other one to be affected too.

I have seen an issue where a browser update caused an application used internally at work to stop working. This affected both Chrome and Edge, but Google and Microsoft pushed out fixes a few days later that resolved the problem. My first thought was therefore that this could be another one of those issues.

But anyway, as there's nothing more to be done in this case, I'll close this issue.

Yours,

Luke

**Closed by LukeWoodward** 2023-06-23 18:53 UTC
